eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: 127.0.0.1:${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  server:
    enable-self-preservation: true